name: Publish Python distributions to PyPI

on:
  workflow_dispatch:
  push:
    
jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - uses: actions/checkout@main

      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
       
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
      - name: Build binary wheel and a source tarball
        run: python setup.py sdist

      - name: Publish distribution to release
        uses: pypa/gh-action-pypi-publish@v1.8.11  # Use an exact tag
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/
